// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CashOperationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CashOperationType
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "ForwardCashOut")]
        ForwardCashOut,
        [EnumMember(Value = "ForwardCashIn")]
        ForwardCashIn
    }
    internal static class CashOperationTypeEnumExtension
    {
        internal static string ToSerializedValue(this CashOperationType? value)
        {
            return value == null ? null : ((CashOperationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CashOperationType value)
        {
            switch( value )
            {
                case CashOperationType.None:
                    return "None";
                case CashOperationType.ForwardCashOut:
                    return "ForwardCashOut";
                case CashOperationType.ForwardCashIn:
                    return "ForwardCashIn";
            }
            return null;
        }

        internal static CashOperationType? ParseCashOperationType(this string value)
        {
            switch( value )
            {
                case "None":
                    return CashOperationType.None;
                case "ForwardCashOut":
                    return CashOperationType.ForwardCashOut;
                case "ForwardCashIn":
                    return CashOperationType.ForwardCashIn;
            }
            return null;
        }
    }
}
