// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CashOutVolumeSize.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CashOutVolumeSize
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "High")]
        High,
        [EnumMember(Value = "Low")]
        Low
    }
    internal static class CashOutVolumeSizeEnumExtension
    {
        internal static string ToSerializedValue(this CashOutVolumeSize? value)
        {
            return value == null ? null : ((CashOutVolumeSize)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CashOutVolumeSize value)
        {
            switch( value )
            {
                case CashOutVolumeSize.Unknown:
                    return "Unknown";
                case CashOutVolumeSize.High:
                    return "High";
                case CashOutVolumeSize.Low:
                    return "Low";
            }
            return null;
        }

        internal static CashOutVolumeSize? ParseCashOutVolumeSize(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return CashOutVolumeSize.Unknown;
                case "High":
                    return CashOutVolumeSize.High;
                case "Low":
                    return CashOutVolumeSize.Low;
            }
            return null;
        }
    }
}
