// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.OperationsRepository;
    using Lykke.Service.OperationsRepository.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IdResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the IdResponseModel class.
        /// </summary>
        public IdResponseModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IdResponseModel class.
        /// </summary>
        public IdResponseModel(string id = default(string))
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

    }
}
