// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LimitOrderCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the LimitOrderCreateRequest class.
        /// </summary>
        public LimitOrderCreateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LimitOrderCreateRequest class.
        /// </summary>
        public LimitOrderCreateRequest(double remainingVolume, System.DateTime createdAt, double volume, double price, bool straight, string matchingId = default(string), string id = default(string), string clientId = default(string), string assetPairId = default(string), string status = default(string))
        {
            RemainingVolume = remainingVolume;
            MatchingId = matchingId;
            Id = id;
            ClientId = clientId;
            CreatedAt = createdAt;
            Volume = volume;
            Price = price;
            AssetPairId = assetPairId;
            Status = status;
            Straight = straight;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemainingVolume")]
        public double RemainingVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MatchingId")]
        public string MatchingId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public string ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedAt")]
        public System.DateTime CreatedAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public double Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPairId")]
        public string AssetPairId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Straight")]
        public bool Straight { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
