// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderType
    {
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class OrderTypeEnumExtension
    {
        internal static string ToSerializedValue(this OrderType? value)
        {
            return value == null ? null : ((OrderType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OrderType value)
        {
            switch( value )
            {
                case OrderType.Buy:
                    return "Buy";
                case OrderType.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static OrderType? ParseOrderType(this string value)
        {
            switch( value )
            {
                case "Buy":
                    return OrderType.Buy;
                case "Sell":
                    return OrderType.Sell;
            }
            return null;
        }
    }
}
