// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.OperationsRepository.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.OperationsRepository;
    using Lykke.Service.OperationsRepository.AutorestClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CashOutRequestStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CashOutRequestStatus
    {
        [EnumMember(Value = "Pending")]
        Pending,
        [EnumMember(Value = "Confirmed")]
        Confirmed,
        [EnumMember(Value = "Declined")]
        Declined,
        [EnumMember(Value = "Processed")]
        Processed,
        [EnumMember(Value = "ClientConfirmation")]
        ClientConfirmation,
        [EnumMember(Value = "CanceledByClient")]
        CanceledByClient,
        [EnumMember(Value = "CanceledByTimeout")]
        CanceledByTimeout,
        [EnumMember(Value = "RequestForDocs")]
        RequestForDocs
    }
}
